export { default as Customer } from './customer/customer';
export { default as Home } from './Home/home';
export { default as InvoiceList } from './invoice/invoice';
export { default as Quotation } from './quotation/quotation';
export { default as Profile } from './profile/profile';
export { default as CreateCustomer } from './customer/create-customer';
export { default as CustomerDetails } from './customer/customer-details';
export { default as CreateOrder } from './Orders/create-order';
export { default as Orders } from './Orders/orders';
export { default as UserOnBoarding } from './auth/user-on-boarding';
export { default as OneTimePassword } from './auth/one-time-password';
export { default as TemplateEditor } from './template-editor/template-editor';
export { default as Services } from './services/offering';
export { default as OrderDetails } from './Orders/order-details';
export { default as CreateInvoice } from './invoice/create-invoice';
export { default as SplashScreen } from './splash/splash';
export { default as FeatureSlide } from './feature-slide/feature-slide';
export {default as InvoiceDetails} from './invoice/invoice-details';
export {default as Success} from './success/success';
export {default as Authentication} from './auth/authentication';