export const BUSINESSTYPE = [
  "Consulting",
  "Information Technology",
  "Marketing & Advertising",
  "Legal Services",
  "Healthcare Services",
  "Education & Training",
  "Travel & Tourism",
  "Real Estate",
  "Logistics & Transportation",
  "Event Management",
  "Financial Services",
  "Human Resources / Staffing",
  "E-commerce",
  "Grocery Store",
  "Clothing & Apparel",
  "Electronics Store",
  "Pharmacy / Medical Store",
  "Furniture & Home Decor",
  "Jewelry & Accessories",
  "Sports & Fitness Equipment",
  "Automobile Manufacturing",
  "Food & Beverage Processing",
  "Textiles & Garments",
  "Electronics & Appliances",
  "Pharmaceuticals",
  "Construction Materials",
  "Chemicals & Plastics",
  "Machinery & Tools",
  "Restaurant",
  "Cafe / Bakery",
  "Hotel / Resort",
  "Catering Services",
  "Food Delivery / Cloud Kitchen",
  "Bars & Breweries",
  "Farming",
  "Dairy & Poultry",
  "Fisheries",
  "Agro Products / Seeds",
  "Agro Equipment Supply",
  "Media & Entertainment",
  "Film & Production",
  "Publishing & Printing",
  "Graphic Design",
  "Photography & Videography",
  "Handicrafts & Artisans",
  "Charity Organization",
  "NGO / Social Services",
  "Religious Organization",
  "Educational Institution",
  "Government Contractor",
  "Freelancer / Independent Professional",
  "Startup / Small Business",
  "Import / Export",
  "Wholesale Trade",
  "Other"
];
export const WORKSTATUS = ["Pending", "Approved", "Rejected", "Cancelled"];

export const ORDERSTATUS = [
  "PENDING",
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
  "DELIVERED"
];

export const QUOTATION_FIELDS = [
  // Company Information
  { label: "Company Title", value: "companyTitle", type: "text" },
  { label: "Company Logo", value: "companyLogo", type: "file" },
  { label: "Company Description", value: "companyDescription", type: "text" },
  { label: "Company Info (address,email,website,phone)", value: "companyInfo", type: "text" },

  // Client Information
  { label: "Client Info(name,email,phone,address)", value: "clientInfo", type: "text" },

  // Quotation Details
  { label: "Quotation Number", value: "quotationNumber", type: "text" },
  { label: "Quotation Date", value: "quotationDate", type: "date" },
  { label: "Valid Until", value: "validUntil", type: "date" },

  // Services Table (line items)
  { label: "Service Info(serviceId,name,description,cost)", value: "serviceInfo", type: "text" },

  // Additional Notes
  { label: "Terms & Conditions", value: "terms", type: "text" },
  { label: "Special Notes", value: "notes", type: "text" },

  // Signature
  { label: "Digital Signature", value: "digitalSignature", type: "file" },
];
export const COLORCODES = [
        "#7C3AED", // Purple
        "#3B82F6", // Blue
        "#10B981", // Emerald Green
        "#F59E0B", // Amber/Orange
        "#EF4444", // Red
        "#6366F1", // Indigo
        "#14B8A6", // Teal
        "#F43F5E", // Rose
        "#22C55E", // Green
        "#8B5CF6", // Violet
    ];


export const COUNTRY_CURRENCY_SYMBOLS: Record<string, string> = {
  AF: "؋",
  AX: "€",
  AL: "L",
  DZ: "دج",
  AS: "$",
  AD: "€",
  AO: "Kz",
  AI: "$",
  AQ: "$",
  AG: "$",
  AR: "$",
  AM: "֏",
  AW: "ƒ",
  AU: "$",
  AT: "€",
  AZ: "₼",
  BS: "$",
  BH: ".د.ب",
  BD: "৳",
  BB: "$",
  BY: "Br",
  BE: "€",
  BZ: "$",
  BJ: "CFA",
  BM: "$",
  BT: "Nu.",
  BO: "Bs.",
  BA: "KM",
  BW: "P",
  BV: "kr",
  BR: "R$",
  IO: "$",
  BN: "$",
  BG: "лв",
  BF: "CFA",
  BI: "FBu",
  KH: "៛",
  CM: "CFA",
  CA: "$",
  CV: "$",
  KY: "$",
  CF: "CFA",
  TD: "CFA",
  CL: "$",
  CN: "¥",
  CX: "$",
  CC: "$",
  CO: "$",
  KM: "CF",
  CG: "CFA",
  CD: "FC",
  CK: "$",
  CR: "₡",
  CI: "CFA",
  HR: "€",
  CU: "$",
  CY: "€",
  CZ: "Kč",
  DK: "kr",
  DJ: "Fdj",
  DM: "$",
  DO: "$",
  TL: "$",
  EC: "$",
  EG: "£",
  SV: "$",
  GQ: "CFA",
  ER: "Nfk",
  EE: "€",
  ET: "Br",
  FK: "£",
  FO: "kr",
  FJ: "$",
  FI: "€",
  FR: "€",
  GF: "€",
  PF: "₣",
  TF: "€",
  GA: "CFA",
  GM: "D",
  GE: "₾",
  DE: "€",
  GH: "₵",
  GI: "£",
  GR: "€",
  GL: "kr",
  GD: "$",
  GP: "€",
  GU: "$",
  GT: "Q",
  GG: "£",
  GN: "FG",
  GW: "CFA",
  GY: "$",
  HT: "G",
  HM: "$",
  HN: "L",
  HK: "$",
  HU: "Ft",
  IS: "kr",
  IN: "₹",
  ID: "Rp",
  IR: "﷼",
  IQ: "ع.د",
  IE: "€",
  IL: "₪",
  IT: "€",
  JM: "$",
  JP: "¥",
  JE: "£",
  JO: "د.ا",
  KZ: "₸",
  KE: "Sh",
  KI: "$",
  KP: "₩",
  KR: "₩",
  KW: "د.ك",
  KG: "с",
  LA: "₭",
  LV: "€",
  LB: "ل.ل",
  LS: "L",
  LR: "$",
  LY: "ل.د",
  LI: "CHF",
  LT: "€",
  LU: "€",
  MO: "P",
  MK: "ден",
  MG: "Ar",
  MW: "MK",
  MY: "RM",
  MV: "Rf",
  ML: "CFA",
  MT: "€",
  IM: "£",
  MH: "$",
  MQ: "€",
  MR: "UM",
  MU: "₨",
  YT: "€",
  MX: "$",
  FM: "$",
  MD: "L",
  MC: "€",
  MN: "₮",
  ME: "€",
  MS: "$",
  MA: "د.م.",
  MZ: "MT",
  MM: "Ks",
  NA: "$",
  NR: "$",
  NP: "₨",
  BQ: "$",
  NL: "€",
  NC: "₣",
  NZ: "$",
  NI: "C$",
  NE: "CFA",
  NG: "₦",
  NU: "$",
  NF: "$",
  MP: "$",
  NO: "kr",
  OM: "ر.ع.",
  PK: "₨",
  PW: "$",
  PS: "₪",
  PA: "$",
  PG: "K",
  PY: "₲",
  PE: "S/",
  PH: "₱",
  PN: "$",
  PL: "zł",
  PT: "€",
  PR: "$",
  QA: "ر.ق",
  RE: "€",
  RO: "lei",
  RU: "₽",
  RW: "FRw",
  SH: "£",
  KN: "$",
  LC: "$",
  PM: "€",
  VC: "$",
  BL: "€",
  MF: "€",
  WS: "T",
  SM: "€",
  ST: "Db",
  SA: "﷼",
  SN: "CFA",
  RS: "дин",
  SC: "₨",
  SL: "Le",
  SG: "$",
  SK: "€",
  SI: "€",
  SB: "$",
  SO: "S",
  ZA: "R",
  GS: "£",
  SS: "£",
  ES: "€",
  LK: "₨",
  SD: "£",
  SR: "$",
  SJ: "kr",
  SZ: "E",
  SE: "kr",
  CH: "CHF",
  SY: "£",
  TW: "NT$",
  TJ: "ЅМ",
  TZ: "Sh",
  TH: "฿",
  TG: "CFA",
  TK: "$",
  TO: "T$",
  TT: "$",
  TN: "د.ت",
  TR: "₺",
  TM: "m",
  TC: "$",
  TV: "$",
  UG: "USh",
  UA: "₴",
  AE: "د.إ",
  GB: "£",
  US: "$",
  UM: "$",
  UY: "$U",
  UZ: "soʻm",
  VU: "Vt",
  VA: "€",
  VE: "Bs.",
  VN: "₫",
  VG: "$",
  VI: "$",
  WF: "₣",
  EH: "د.م.",
  YE: "﷼",
  ZM: "ZK",
  ZW: "$",
  XK: "€",
  CW: "ƒ",
  SX: "ƒ",
};


export const PLAN_DETAILS={
  free:{
    planId:"FREE",
    planTitle:"15 days free trial",
    planName:"Free Plan",
    planDescription:"15 days free trial",
    durationInDays:15,
    price:0,
    featureList:[
      "Full feature access",
      "Unlimited projects",
      "Unlimited team members",
    ]

  },
  premium:{
    monthly:{
      planId:"PREMIUM_MONTHLY",
      planName:"Premium Plan",
      planTitle:"$10/month",
      planDescription:"30 days premium plan",
      durationInDays:30,
      price:30,
      featureList:[
        "Full feature access",
        "Unlimited users",
        "Unlimited projects",
        "Unlimited tasks",
        "Unlimited team members",
      ]
    },
    yearly:{
      planId:"PREMIUM_YEARLY",
      planName:"Premium Plan",
      planTitle:"$100/year",
      planDescription:"365 days premium plan",
      durationInDays:365,
      price:365,
      featureList:[
        "Full feature access",
        "Unlimited users",
        "Unlimited projects",
        "Unlimited tasks",
        "Unlimited team members",
      ]
    }
  }
}