export const BUSINESSTYPE = [
  "Consulting",
  "Information Technology",
  "Marketing & Advertising",
  "Legal Services",
  "Healthcare Services",
  "Education & Training",
  "Travel & Tourism",
  "Real Estate",
  "Logistics & Transportation",
  "Event Management",
  "Financial Services",
  "Human Resources / Staffing",
  "E-commerce",
  "Grocery Store",
  "Clothing & Apparel",
  "Electronics Store",
  "Pharmacy / Medical Store",
  "Furniture & Home Decor",
  "Jewelry & Accessories",
  "Sports & Fitness Equipment",
  "Automobile Manufacturing",
  "Food & Beverage Processing",
  "Textiles & Garments",
  "Electronics & Appliances",
  "Pharmaceuticals",
  "Construction Materials",
  "Chemicals & Plastics",
  "Machinery & Tools",
  "Restaurant",
  "Cafe / Bakery",
  "Hotel / Resort",
  "Catering Services",
  "Food Delivery / Cloud Kitchen",
  "Bars & Breweries",
  "Farming",
  "Dairy & Poultry",
  "Fisheries",
  "Agro Products / Seeds",
  "Agro Equipment Supply",
  "Media & Entertainment",
  "Film & Production",
  "Publishing & Printing",
  "Graphic Design",
  "Photography & Videography",
  "Handicrafts & Artisans",
  "Charity Organization",
  "NGO / Social Services",
  "Religious Organization",
  "Educational Institution",
  "Government Contractor",
  "Freelancer / Independent Professional",
  "Startup / Small Business",
  "Import / Export",
  "Wholesale Trade",
  "Other"
];
export const EVENRSTATUS = ["Pending", "Approved", "Rejected", "Cancelled"];